# --- DARE-Linear (профиль по глубине) ---
merge_method: dare_linear
base_model: &BASE_MODEL /workspace/Mistral-Small-3.2-24B-Instruct-2506
dtype: bfloat16

models:
  - model: &VISTRAL /workspace/Vistral-24B-Instruct
    # Вклад Vistral: больше внизу, меньше к верху
    parameters:
      weight:
        - filter: self_attn
          value: [0.65, 0.60, 0.55, 0.50, 0.45]
        - filter: mlp
          value: [0.60, 0.55, 0.50, 0.45, 0.40]
  - model: &CYDONIA /workspace/Cydonia-24B-v4.2.0
    # Вклад Cydonia: наоборот — меньше внизу, больше к верху
    parameters:
      weight:
        - filter: self_attn
          value: [0.35, 0.40, 0.45, 0.50, 0.55]
        - filter: mlp
          value: [0.40, 0.45, 0.50, 0.55, 0.60]

parameters:
  # Разреживание дельт DARE: можно тоже «профилировать» и/или
  # делать его отличным для attn и mlp (значения — примерные)
  density:
    - filter: self_attn
      value: [0.65, 0.60, 0.60, 0.55, 0.55]
    - filter: mlp
      value: [0.60, 0.55, 0.55, 0.50, 0.50]
  normalize: true   # веса нормализуются автоматически

# Словарь объединяем, чтобы сохранить +2 токена Vistral
tokenizer_source: union
