# --- Исправленный конфиг для SLERP слияния ---

# 1. Метод слияния по умолчанию.
#    Валидатор требует его наличие, даже если он будет переопределен ниже.
merge_method: slerp
dtype: bfloat16
base_model: /workspace/Vistral-24B-Instruct

slices:
  # Мы по-прежнему используем один "срез" для всей модели
  - sources:
      # 2. Явное указание диапазона слоев для КАЖДОЙ модели.
      #    Для полного слияния нужно указать все слои.
      #    В этих моделях 40 слоев (с 0 по 39).
      - model: /workspace/Vistral-24B-Instruct
        layer_range: [0, 39]
      - model: /workspace/Cydonia-24B-v4.2.0
        layer_range: [0, 39]
    # Метод и параметры теперь применяются к этому конкретному срезу
    merge_method: slerp
    parameters:
      t: 0.5 # Коэффициент слияния. 0.5 = ровно посередине.

# Объединяем словари, чтобы сохранить все токены.
tokenizer:
  source: union
