# --- Gradient SLERP: Vistral (RU) x Cydonia (RP) ---
merge_method: slerp
base_model: /workspace/Vistral-24B-Instruct   # якорь SLERP (0.0 = чистый Vistral)
dtype: bfloat16

models:
  - model: /workspace/Vistral-24B-Instruct
  - model: /workspace/Cydonia-24B-v4.2.0

parameters:
  # Плавный профиль "снизу больше Vistral (RU), сверху больше Cydonia (RP)"
  # 5 узлов будет равномерно интерполировано на все слои трансформера.
  t:
    - filter: self_attn
      value: [0.35, 0.45, 0.55, 0.60, 0.65]  # ниже — ближе к Vistral, выше — к Cydonia
    - filter: mlp
      value: [0.30, 0.45, 0.55, 0.60, 0.60]
    - value: 0.50  # дефолт на прочие тензоры (если какие-то не попали под фильтры)

  # SLERP и для embed/lm_head при разных словарях (доступно только для 2 моделей)
  embed_slerp: true

# Собираем объединённый словарь, чтобы корректно свести "+2 токена" у Vistral
tokenizer_source: union
